HOSTS:
  centos-65-x64:
    roles:
      - master
    platform: el-6-x86_64
    box : centos-65-x64-vbox436-nocm
    image : centos
    hypervisor : docker
    docker_cmd: [/sbin/init]
CONFIG:
  type: foss
