HOSTS:
  ubuntu-12-10:
    platform: ubuntu-12.10-x64
    image: ubuntu:12.10
    hypervisor: docker
    docker_image_commands:
      - 'echo "deb http://old-releases.ubuntu.com/ubuntu/ precise main restricted" > /etc/apt/source.list'
      - 'echo "deb-src http://old-releases.ubuntu.com/ubuntu/ precise main restricted" >> /etc/apt/source.list'
    docker_cmd: '/usr/sbin/sshd -D'
CONFIG: 
  type: foss
