HOSTS:
    ubuntu-server:
        roles:
         - master
        platform: ubuntu-12.10-x64
        image: ubuntu-upstart:12.10
        hypervisor: docker
        docker_cmd: [/sbin/init]
CONFIG:
  type: foss
